// <auto-generated />
namespace HospiceNiagara.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class wipe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(wipe));
        
        string IMigrationMetadata.Id
        {
            get { return "201503151812462_wipe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
